### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-paper#73]
- [x] Export to Overleaf
- [x] Add Acknowledgments
- [x] Table 1: Add links
- [x] Fig 3 label is on dotted line
- [x] Add line numbers (perhaps make 2 version at last minute)
- [x] Consistent use of em dash (—). It should be specifically that charachter and have no spaces around it.
- [x] The FaceNet methods section has several variables not presented (e.g. first_time_face)
- [x] Rebuild jupyter book and link

Citation related issues:
- [x] fMRIprep section needs references properly cited
- [x] Manually check all refs
- [x] Markiewickz citations look odd to. e.g.: C. Markiewicz et al., 2021; C. J. Markiewicz et al., 2021 - statsmodels and fitlins respsectively
